//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepresentativeOffice.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusRepairRequest
    {
        public int IDStatusRepairRequest { get; set; }
        public int IDRepairRequest { get; set; }
        public int IDRepairStatus { get; set; }
        public System.DateTime DateAddStatus { get; set; }
        public string Comment { get; set; }
    
        public virtual RepairRequest RepairRequest { get; set; }
        public virtual RepairStatus RepairStatus { get; set; }
    }
}
